var names = [];
names.push("sakshi");
names.push("rohan");
console.log(names);
var names1 = [];
names1.push("sakshi");
names1.push(12);
console.log(names1);
var nums = [4, 6, 7, 8];
console.log(nums[3]);
